-- load varieties list (sourced from on https://github.com/collabriculture/australian-grape-vine-varieties)
insert into variety (name) values
    ('Chenin Blanc'),
    ('Carignan'),
    ('Carmenere'),
    ('Clairette'),
    ('Colombard'),
    ('Durif'),
    ('Fiano'),
    ('Grenache'),
    ('Gerwurztraminer'),
    ('Malbec'),
    ('Marsanne'),
    ('Mataro/Mourvedre'),
    ('Merlot'),
    ('Montepulciano'),
    ('Muscat '),
    ('Nero d''Avola'),
    ('Petit Verdot'),
    ('Pinot Gris (Grigio)'),
    ('Pinot Noir'),
    ('Riesling'),
    ('Roussanne'),
    ('Ruby Cabernet'),
    ('Sangiovese'),
    ('Sauvignon Blanc'),
    ('Semillon'),
    ('Shiraz'),
    ('Tempranillo'),
    ('Touriga Nacional'),
    ('Traminer'),
    ('Verdelho'),
    ('Vermentino'),
    ('Viognier'),
    ('Zinfandel'),
    ('Other ')
;
